### ISSUE TITLE
Reevaluate dimension/biome white/blacklisting

### ISSUE THREAD

**Issue by alcatrazEscapee** [alcatrazEscapee/primal-winter#101]
Does it function, is it necessary, is it failsafe, and does it _actually_ work as user-intended.

**Comment by PinkDisorder** [comment]
Is there any chance of getting the recent fix backported to 1.20.1? Currently, the `nonWinterDimensions` array in the config gets overwrote every run.

**Comment by Burakkyya** [comment]
Please backport 1.21 update to 1.20.1... Pretty please, please?
