### ISSUE TITLE
primal-winter config nonWinterDimensions field does not work as intended

### ISSUE THREAD

**Issue by Burakkyya** [alcatrazEscapee/primal-winter#105]
I am trying to make a modpack where you try to survive through an post-apocalyptic world and try to find a better suitable world to live in through Ad Astra mod, but even when I add the dimensions into the primalwinter.toml, Ad Astra dimensions still turn into a primal winter dimension. (Blizzards in Moon, Venus, Mercury [Even on orbits])

My nonWinterDimensions field : 

`nonWinterDimensions = ["minecraft:nether", "minecraft:end", "ad_astra:mars", "ad_astra:mercury", "ad_astra:mercury_orbit", "ad_astra:moon", "ad_astra:mars_orbit", "ad_astra:moon_orbit", "ad_astra:glacio_orbit", "ad_astra:venus", "ad_astra:venus_orbit"]`

**Comment by Burakkyya** [comment]
This issue occurs on 1.20.X

**Comment by alcatrazEscapee** [comment]
See #101
