### ISSUE TITLE
Primal Winter (1.21.1) causes rainstorms in every overworld biome.

### ISSUE THREAD

**Issue by asa-jorg** [alcatrazEscapee/primal-winter#108]
Primal Winter causes rainstorms instead of snowstorms in every overworld biome in the 1.21.1 version.

**Comment by alcatrazEscapee** [comment]
Cannot reproduce - please upload a log file with the issue.

**Comment by asa-jorg** [comment]
[latest.log](https://github.com/user-attachments/files/16985705/latest.log)
Could not reproduce myself, but discovered that Biomes O' Plenty biomes do not generate with snow layers.
![2024-09-12_14 40 39](https://github.com/user-attachments/assets/d5e420ea-d5c4-406a-a8ef-1f47140a83b1)
