### ISSUE TITLE
No structures

### ISSUE THREAD

**Issue by gloompy7** [alcatrazEscapee/primal-winter#112]
Hi

I am using your mod in a modpack I made for me and the boys, but we tried finding a village, and couldn't find any. I used commands to try to locate a village, but It found none. Is this intentional for your mod or not, maybe it is from another? If it is though, is there a way to enable structures?

Thanks,
-Gloompy7

**Comment by alcatrazEscapee** [comment]
This mod only modifies villages, replacing them all with vanilla's "abandoned" ones. It makes no other changes to structure generation or has a way to "enable" structures.

**Comment by gloompy7** [comment]
Thank you
