### ISSUE TITLE
Hostile Mobs spawn Constantly

### ISSUE THREAD

**Issue by destinycraftia** [alcatrazEscapee/primal-winter#116]
I'm unsure if this is an intentional feature, but whenever I have Primal Winter active, hostile mobs spawn excessively, and I'm wondering if you could possibly make this something that could be configured, because I do not see any way to do so in the config already. If not I think that it would be a really good feature that would significantly increase the usability for the mod and make it better for the general public.

**Comment by VirusCity** [comment]
I am seeing the same issue, constant hostile mob spawning. Would love the ability to turn that off.

**Comment by alcatrazEscapee** [comment]
https://minecraft.wiki/w/Thunderstorm

> Unlike during regular rainstorms or snowstorms, the light level from the sky is treated as if it were 0 for the purposes of hostile mob spawning, which allows hostile [mobs](https://minecraft.wiki/w/Mobs) to spawn at any time of the day.

This is an effect of thunderstorms in vanilla.

**Comment by VirusCity** [comment]
I was seeing this with the weather override disabled and on clear weather. I have remedied the issue with the Mob Filter mod.
