### ISSUE TITLE
[Question] [1.15.2] Will this mod break a world if removed?

### ISSUE THREAD

**Issue by HockeyZman2000** [alcatrazEscapee/primal-winter#16]
Hi! I'm really interested in this mod specifically but I have yet to download. I host a modded server (around 110 mods) with a group of friends and plan on having a "Winter Update" with quests and whatnot for the holiday season when it rolls around every year. I only ask this question because I would like to remove it after the real-life winter season is over and have the landscape in the world return to normal. Is this what happens without the mod? And/or will this cause any lasting issues for the world or for other mods that you know of? I looked at a couple other winter mods before this one and I think this looks the best, plus having the fog and snowy mobs everywhere. Please let me know!

**Comment by alcatrazEscapee** [comment]
Well yes,

- This mod will not apply retroactively. Already generated chunks will only have the various snowy effects, none of the snowy blocks.
- Any blocks added by this mod and placed in new chunks (snowy dirt, snowy logs, snowy leaves, etc.) are going to be removed when you remove this mod.

If you *still* want to use it, then you could do a "find / replace" both before and after as all this mods blocks (e.g. "Snowy Birch Log") are 1-1 mappable to vanilla blocks.

But that sounds like a lot of work and I generally wouldn't recommend using this for this purpose, no.

**Comment by HockeyZman2000** [comment]
Okay thank you for the response. Just a couple more questions. Will the "snowy effects" that happen in generated chunks still accumulate surface snow on the ground like a normal vanilla snowstorm/blizzard? And then let's say if I wanted the block replacements from the mod to not happen but still get the snowy effects, would that be possible via a config or something or no?

**Comment by alcatrazEscapee** [comment]
Primal Winter does the equivalent of `/gamerule doWeatherCycle false` and `/weather thunder` to enable storms. Everything related to that (fog, snow accumulation) is predicate on the (vanilla) weather handling.

> And then let's say if I wanted the block replacements from the mod to not happen but still get the snowy effects, would that be possible

Don't generate any new chunks with this mod. (pre generate + world border). Otherwise No.

**Comment by HockeyZman2000** [comment]
Thanks for the information and help!
