### ISSUE TITLE
[suggestion] Please make separate projects for Forge and Fabric.

### ISSUE THREAD

**Issue by ProsperCraft** [alcatrazEscapee/primal-winter#17]
When updating almost 200 mods in my modpack on the Twitch launcher, I go through and click the up arrows to update them all, when the project has mixed forge/fabric it downloads the forge mod in my fabric modpack, and the fabric mod in my forge modpack, breaking the packs, please separate the projects.

**Comment by alcatrazEscapee** [comment]
No, sorry.
