### ISSUE TITLE
Config option to disable snow/wind sounds while indoors

### ISSUE THREAD

**Issue by Dhs92** [alcatrazEscapee/primal-winter#2]
The sound is nice when you're outside fighting the storm, but it seems to get a bit tiring rather quickly. Would be nice if we could get a config option to disable the sound while indoors, if possible.

**Comment by alcatrazEscapee** [comment]
This actually interests me why it isn't already the case. The sound is using the exact same mechanisms as minecraft rain splashing noises (and in fact, both still play), and that one tends to be much more responsive to not playing when the player is away from the storm. I can see two possible reasons:
- The storm sound is much longer (~6 s opposed to < 1s) so it appears much less responsive.
- The storm sound is quite a bit louder, meaning it needs to be farther away to be unheard.

That said, I need to look into this, just not sure how it will pan out...

**Comment by alcatrazEscapee** [comment]
b3333a9644a5a957cd7557efd0fcec6536650c36 should resolve for fabric, will work on getting that back to forge.
