### ISSUE TITLE
How do you revert world to normal?

### ISSUE THREAD

**Issue by Animelabose** [alcatrazEscapee/primal-winter#22]
So I was just going on with my day and decided to go to my modded survival world, and all the sudden it started snowing really hard. I realized I forgot to remove this mod from the mods folder and closed minecraft, removed the mod from my folder, and rejoined my minecraft world. It kept thundering so I decided to sleep in a minecraft bed, and the thunder never ended. I think my world got ruined by this mod and the rain will never stop (I am using a big 35 mods modpack I made in this world, and it is really hard to survive in the rain due to the really strong modded mobs spawning in the thunder) I really want to turn my world back to normal so please help me with this. Thank you.
![image](https://user-images.githubusercontent.com/74474700/99886105-7a184d80-2bff-11eb-80ba-65455012f3c8.png)

**Comment by alcatrazEscapee** [comment]
After you've removed the mod,
`/gamerule doWeatherCycle true`
`/weather clear`
