### ISSUE TITLE
[Issue] Primal Winter mod ruined my world

### ISSUE THREAD

**Issue by Animelabose** [alcatrazEscapee/primal-winter#23]
I joined my minecraft modded world when I forgot to remove the primal winter mod from my mods folder. My world became infinitely snowy and that's not the beginning of it. When I removed the mod from my minecraft world, the world stayed in a thunderstorm state and will never stop thundering no matter what. I need help please tell me how to fix this. Modded mobs are much stronger in the storms so I need the thunder to stop. Please help!

**Comment by alcatrazEscapee** [comment]
aka "mod did what it said on the tin". ya might want to take backups next time.

See #22.
