### ISSUE TITLE
Trying to start a server with this mod, breaks the world generation.

### ISSUE THREAD

**Issue by Soulayee** [alcatrazEscapee/primal-winter#25]
![minecraft gen glitch](https://user-images.githubusercontent.com/74695529/100722060-06034580-3375-11eb-8b30-681cd8186fd6.png)

I'm using a couple mods, and I've tried it with only this mod and also without. With the mod broke the generation, without it didn't.

**Comment by alcatrazEscapee** [comment]
This issue is lacking a number of this to be comprehensible.
- Minecraft version
- Mod version
- Mod loader (forge / fabric) and preferably version
- Logs of any kind.

Moreover, this looks like some form of world corruption or registry ID mismatch that has nothing to do with this mod.
