### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [alcatrazEscapee/primal-winter#28]
[crash-2021-01-08_11.50.56-client.txt](https://github.com/alcatrazEscapee/primal-winter/files/5789146/crash-2021-01-08_11.50.56-client.txt)

![image](https://user-images.githubusercontent.com/51277766/104058928-54dca000-51a9-11eb-89df-b6415f2c1509.png)

![image](https://user-images.githubusercontent.com/51277766/104059062-89505c00-51a9-11eb-9478-83193dc29044.png)

Not really sure what this is caused by.

Dynamic Surroundings will also completely override this mod's wind sound effects.

**Comment by alcatrazEscapee** [comment]
Need a lot more information here,

- How did you get the crash? Is it reproducible?
- What other mods were installed? Does the crash occur without them? Is there specific mods that predicate the crash? (At a wild guess, try serene seasons)
- Can you provide the full `latest.log` from the logs folder?

**Comment by MagmaSlime123** [comment]
1. I have no idea. Came out of nowhere. Litterally.
2. I'll give the mods folder if needed.
3. [latest.log](https://github.com/alcatrazEscapee/primal-winter/files/5789512/latest.log)

**Comment by CaoticDeity** [comment]
had a similar thing happen here's the crash report

[crash-2021-01-22_22.48.17-client.txt](https://github.com/alcatrazEscapee/primal-winter/files/5859690/crash-2021-01-22_22.48.17-client.txt)

And here's my latest.log

[latest.log](https://github.com/alcatrazEscapee/primal-winter/files/5859692/latest.log)

**Comment by alcatrazEscapee** [comment]
@CaoticDeity your crash is not similar in the slightest, and if I had to guess is an optifine compatibility issue.

In either case I'm not quite sure what to do here as I've not been able to reproduce any crashing myself.

**Comment by alcatrazEscapee** [comment]
I've got nothing for either of these. Can't reproduce. :shrug:
