### ISSUE TITLE
Enlever les particule de la tempête de neige 

### ISSUE THREAD

**Issue by Ronshark** [alcatrazEscapee/primal-winter#29]
Bonjour a tous

Je me demandais, comment enlever les particule de la tempête de neige

je vous remercie pour toutes aides.

**Comment by alcatrazEscapee** [comment]
If you're on Forge, in the `-client` config, there are various options for rendering changes. If it doesn't exist in the config, it's not possible. Otherwise that's kinda what this mod does.

**Comment by Ronshark** [comment]
Il y a bien le client mais je ne sais pas comment changer les paramètres et je ne suis à développeur
