### ISSUE TITLE
[Suggestion] Disable snow from layering config

### ISSUE THREAD

**Issue by Necxx** [alcatrazEscapee/primal-winter#30]
It would be nice to see you add somewhere in the config something to stop from layering after generating. That way I can play with this mod without worries in the long term, without constantly clearing snow.
Unless there is already a system in place?

**Comment by alcatrazEscapee** [comment]
This is going to sound dumb.

But I didn't *think* this existed, hence why I've left this as an enhancement. But it does! It's found in the server config (inside the save folder), and it's called `enableSnowAccumulation`. Thanks to #24.

So uh.
Yeah.
