### ISSUE TITLE
Configs not saving for version 1.1.2 (minecraft 1.15.2 with forge)

### ISSUE THREAD

**Issue by TzeChampion** [alcatrazEscapee/primal-winter#33]
Ok so heres the issue : the configs do not allow any changes in this version. 
Even if i dont change anything, the logs says that the default configs are incorrect and reset them to the "correct default value"
here are the logs : 
[Logs with normal Config File.txt](https://github.com/alcatrazEscapee/primal-winter/files/6098090/Logs.with.normal.Config.File.txt)
[Logs with modified Config file.txt](https://github.com/alcatrazEscapee/primal-winter/files/6098091/Logs.with.modified.Config.file.txt)

I tried placing the additionnal biomes before the default ones, after the default ones, deleting the default biomes and trying to add vanilla biomes. None of those worked. The 1.16 version worked just fine but i have no clue why the 1.15 version doesnt.

**Comment by alcatrazEscapee** [comment]
Not supporting 1.15 anymore, sorry.

(As is probably very clear, I just don't have the time to support multiple modloaders and/or versions across my mods.)
