### ISSUE TITLE
Suggestion - Wind sound should follow rain sound rules

### ISSUE THREAD

**Issue by codewolf219** [alcatrazEscapee/primal-winter#34]
https://github.com/alcatrazEscapee/primal-winter/blob/55b77f917d216fa2ebc2f52e65d7e3e4ea65369c/src/main/java/com/alcatrazescapee/primalwinter/mixin/client/renderer/WorldRendererMixin.java#L258

As implemented, if I put a piece of glass at the top of a column and go down to bedrock, I still hear wind.  The sound would make more sense if it occurred like rain sounds

**Comment by alcatrazEscapee** [comment]
This is intentionally not the same as rain sounds, as they only play at the surface level. Which also means, if you say, fly up a couple hundred blocks into the air, in *the very depths of the storm*, there are no rain/wind sounds. Moreover, the wind sounds are tied to the same checks that are used for the fog, which for obvious reasons, cannot simply be based on the top block in the column (i.e. as rain is). For these reasons, the sky light check was chosen as a proxy for how outside one is, and thus how close to the storm one is.

So, I'm not convinced that it should.

**Comment by codewolf219** [comment]
Alternative suggestion:  Make wind originate from any air block that is above the motion blocking heightmap.  This would eliminate the need for the light level check and solve both scenarios - far under a glass block (think skylight window) would be silent, and far into the sky would still have wind sounds.  It seems to me that it would also seem more realistic in a shallow cave immersed in darkness as well, that you would hear wind blowing against the outside and could find your way to the surface.  Just a thought.
