### ISSUE TITLE
[Suggestion] Blacklist Toggle for Biome List

### ISSUE THREAD

**Issue by Snorps** [alcatrazEscapee/primal-winter#35]
It would be awesome if you could add a toggle to turn the biome list from a blacklist into a whitelist, to make it easier to only have a handful of biomes winterified. Thanks ^^

**Comment by Elfinlocks** [comment]
Seconding this request - I'd love to use this mod in my pack, but it would be very difficult to relegate it to a specific place or dimension, by noting only specific biomes which should not be winterified.
