### ISSUE TITLE
[𝙨𝙪𝙜𝙜𝙚𝙨𝙩𝙞𝙤𝙣] server client visual functionality

### ISSUE THREAD

**Issue by NPC-Master3304** [alcatrazEscapee/primal-winter#37]
so obviously putting this mod on the client and joining a vanilla server won't transfer the mechanics and the new blocks, but from what I'm seeing, it should be possible to apply the fog, snow, sky, and biome changes (client-sided) when you join a server. you could implement an option in the config for this. In addition to this, u could also add an option to make it snow all the time on servers client-wise than for it to only snow when it starts raining/snowing on the server (of course snow layers won't generate). adding onto that, you could either make a resource pack or implement it in fabric that replaces the default textures with the ones from the mod like replacing the oak logs texture with the snowy oak logs (making this as an option in the config would be nice as well if you're doing this from fabric and not a resource pack).

**Comment by alcatrazEscapee** [comment]
> you could implement an option in the config for this

No, config based registrations are discouraged by Forge, and not going to happen.

> an option to make it snow all the time on servers

All Primal Winter does is the following:

```
/weather thunder
/gamerule doWeatherCycle false
```

so, yes, entirely possible for a server to do.

> you could either make a resource pack or implement it in fabric that replaces the default textures

Which makes it now not a server only mod anymore.

In short, no, I see no benefit to be gained from making this a server only mod. If you want the features of this mod, you can install it on both sides. If you want *just* the server side only features you can:

- Make a datapack that turns all the biomes to snowy versions (this is possible to do server side only).
- Run the above commands in-game to create endless winter.
