### ISSUE TITLE
Error charging the mod 1.15.2

### ISSUE THREAD

**Issue by Qwarkkkk** [alcatrazEscapee/primal-winter#38]
Hey I have a little probleme when i try to load the game with the mod, it says that to me :

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: primalwinter:snowy_spruce_leaves
Code de sortie : -1

And there is the crash repport :
[crash-2021-04-26_11.31.51-client.txt](https://github.com/alcatrazEscapee/primal-winter/files/6375923/crash-2021-04-26_11.31.51-client.txt)

**Comment by alcatrazEscapee** [comment]
Not supporting 1.15 anymore, sorry.

(As is probably very clear, I just don't have the time to support multiple modloaders and/or versions across my mods.)
