### ISSUE TITLE
biomes in non snowy whitelist are still snowy, and the snow still accumulates, but the effects are gone

### ISSUE THREAD

**Issue by JSJBDEV** [alcatrazEscapee/primal-winter#39]
![image](https://user-images.githubusercontent.com/16166991/117349959-e633f880-aea3-11eb-9617-1abbaa996a30.png)
this is with minecraft:desert in the list - this is a desert, and the snow is still building up

**Comment by alcatrazEscapee** [comment]
Mod loader?
Minecraft version?
Mod loader version?
Newly generated chunks since adding biome to the whitelist?

**Comment by JSJBDEV** [comment]
Ah sorry yes:
Mod Loader/version: Fabric 1.16.5 (JumpLoder on CurseForge)
This world was generated after adding desert to the whitelist, before the game was even booted

**Comment by JSJBDEV** [comment]
this wasnt a crash but I an provide a log if you wish to see other mods and extra details

**Comment by JSJBDEV** [comment]
![image](https://user-images.githubusercontent.com/16166991/117385125-58c0ca80-aedc-11eb-8fe7-bc4276324aa2.png)
so I forked the mod (locally) and made it so it did this, Im not sure if you ever intended it to do this, I can make a pull request if you think this looks about right, but it might need some modification, it does feel kinda wierd that I can see where there was previously storm now but Im thinking thats not an easy fix

I feel like maybe itd work better if I put the fog back in, but ive at least "fixed" the issue where non snowy biomes would still accumulate snow, perhaps it doesnt need to necessarily clear of snow on the floor?

another observation im seeing is that actually some of the desert floor is clear, but some of it is still accumulating snow, albeit without the particles

**Comment by alcatrazEscapee** [comment]
Not supporting fabric anymore, sorry. (But by all means, keep your fork).

(As is probably very clear, I just don't have the time to support multiple modloaders and/or versions across my mods.)
