### ISSUE TITLE
Snow and ice generates above nether bedrock

### ISSUE THREAD

**Issue by River25** [alcatrazEscapee/primal-winter#4]
This happens most of the time if you go above the nether bedrock however sometimes it doesn't appear automatically if the chunk is not loaded.

**Comment by alcatrazEscapee** [comment]
Minecraft version?
Forge or Fabric?
Mod version?

**Comment by River25** [comment]
Minecraft Version: 1.16.1
Fabric    Version: 0.8.9
Mod Version primalwinter-fabric-1.16.1-1.0.0.jar

**Comment by alcatrazEscapee** [comment]
I cannot reproduce. Have you made sure that the nether biomes are blacklisted from winter transformations in the config?

```toml
nonWinterBiomes = "minecraft:the_end,minecraft:small_end_islands,minecraft:end_barrens,minecraft:end_highlands,minecraft:end_midlands,minecraft:nether_wastes,minecraft:soul_sand_valley,minecraft:crimson_forest,minecraft:warped_forest,minecraft:basalt_deltas"
```

**Comment by alcatrazEscapee** [comment]
In any case, should be resolved by https://github.com/alcatrazEscapee/primal-winter/releases/tag/v1.1.0-fabric
