### ISSUE TITLE
[Issue] Snowy Vines process the snow layer under them as a full block.

### ISSUE THREAD

**Issue by Wizelf402** [alcatrazEscapee/primal-winter#40]
Version: 1.16.4 (Possibly 1.16.5 as well)

Forge Version: 35.1.37 and beyond

Steps to recreate:
- Install Primal Winter
- Install Snow Under Trees to make it easier to see the glitch.
- Find a biome where the trees have vines, and try to move around.

---------------

Essentially, there's a glitch in Primal Winter, where snowy vines process layers of snow in the block directly under them as a full block from certain directions, essentially resulting in invisible blocks in place of snow layers. This glitch makes navigating jungles and swamps particularly frustrating.

**Comment by alcatrazEscapee** [comment]
I'm not supporting 1.16 anymore; and have not been able to reproduce or see evidence of this issue myself in this or later versions. As such, I'm closing this issue.
