### ISSUE TITLE
Snow rendering acting up when brightness is changed

### ISSUE THREAD

**Issue by Wizelf402** [alcatrazEscapee/primal-winter#41]
Version: 1.16.4 and beyond

Forge: 35.1.37 and beyond

Primal Winter Version: 2.0.5

How to recreate:
- Install Primal Winter
- Set the Brightness to MOODY

So, essentially, Primal Winter has this really weird bug, where the snowstorm is being affected by the shadows coming from the thunderstorm itself. To sum things up, when you turn the brightness down, the snow particles get kinda... screwed up. Their textures darken, and they start to look, like, almost black.

![2021-05-17_09 54 46](https://user-images.githubusercontent.com/79106168/118500660-f8a90000-b6f5-11eb-8bee-6fc1f6e04688.png)
(A picture of the snowstorm with Moody Brightness)

**Comment by alcatrazEscapee** [comment]
![hrrmmmm](https://user-images.githubusercontent.com/35673674/120529223-425a4180-c3aa-11eb-8174-f2ebadcca1ad.png)


Left = Primal Winter, Right = Vanilla
Top = 100% Brightness, Bottom = 0% Brightness (Moody)

So yeah... there's a problem.

Notably, snow in the bottom left picture which is rendered atop the snow blocks themselves, is colored correctly. I have... no idea why this is, nor do I have a lot of experience with rendering. This might be problematic...
