### ISSUE TITLE
Make new blocks optional

### ISSUE THREAD

**Issue by adriankiezik** [alcatrazEscapee/primal-winter#48]
Make replacing blocks in WorldGenRegionMixin class configurable.

The main reason to do that, is because you can't place tree saplings on snowy grass block.
Also, when the new tree grow, it doesn't have new snowy leaves block, so it looks quite weird.
And etc.

**Comment by alcatrazEscapee** [comment]
> The main reason to do that, is because you can't place tree saplings on snowy grass block.

I don't see a problem. You can break each of the snowy blocks and retrieve their counterpart.

> Also, when the new tree grow, it doesn't have new snowy leaves block, so it looks quite weird.

Believe it or not, trees do not grow snow. Weather adds snow. And since #42 is done, it will.

So no, I see no point to this.
