### ISSUE TITLE
[Suggestion] Stop ice/snow from melting

### ISSUE THREAD

**Issue by sanedsf** [alcatrazEscapee/primal-winter#49]
Are there any future plans to add the option of ice/snow **not** melting?
It fits with the theme of a never ending snowstorm so the blocks don't even have the time to melt.

There is the [Permafrost](https://www.curseforge.com/minecraft/mc-mods/permafrost) mod but it has not seen any updates in 2 years.

**Comment by alcatrazEscapee** [comment]
No, there is no such plans.

**Comment by codewolf219** [comment]
@sanedsf Not to toot my own horn, but I have made a mod that can do what you want. https://www.curseforge.com/minecraft/mc-mods/icecontrol

**Comment by sanedsf** [comment]
@codewolf219 that's nice! But I was looking a similar effect for fabric.
