### ISSUE TITLE
Ice under Oceans  has lines seperating every chunk (Visual Glitch)

### ISSUE THREAD

**Issue by River25** [alcatrazEscapee/primal-winter#5]
![2020-08-06_23 17 27](https://user-images.githubusercontent.com/69334479/89605310-3b6eab00-d83b-11ea-8823-33903c7c4759.png)

**Comment by alcatrazEscapee** [comment]
- I can't reproduce at all
- Ice rendering is well known to be funky in vanilla ([MC-38022](https://bugs.mojang.com/browse/MC-38022))
- This mod doesn't change anything to do with ice or underwater rendering that would affect this.
