### ISSUE TITLE
Fog effect and glass

### ISSUE THREAD

**Issue by Airyetruetree** [alcatrazEscapee/primal-winter#50]
So i made a giant glass demi-sphere above ground and found out that even without any opening to the outside, there is still that annoying fog effect inside the ball. Any idea of to supress it while indoor under the glass ? I'm on forge btw. Thanks in advance for any tips.

**Comment by alcatrazEscapee** [comment]
Fog is based on sky light. So yes, transparent blocks block it. It is not a indefinite flood fill with connection to the sky, nor is it positional due to sky access as fog is applied globally in minecraft.
