### ISSUE TITLE
monde englouti

### ISSUE THREAD

**Issue by carnivorchild** [alcatrazEscapee/primal-winter#51]
Could you make a mod similar to primal winter but which engulfed the biome underwater while still allowing the vanilla and mod structure to spawn normally and spawn mobs if they dried up an area?

**Comment by alcatrazEscapee** [comment]
This has absolutely nothing to do with primal winter, my mod's issues tabs are not a place to solicit low effort mod requests.

**Comment by carnivorchild** [comment]
sorry i didn't mean to upset you. Primal Winter is an awesome mod that I really like. I can't find any other forge 1.16.5 mode that changes the environment of mincraft like yours. a submerged, toxic or desert world, either they are very old, or they break the biom, structure and crowd no longer appear correctly. if I am offering this idea to you, it is because I have confidence in your ability to create well-made post-apocalyptic mods. sorry again
(I use google translate so sorry if my sentences are not very understandable)
