### ISSUE TITLE
Snowy leaf variants look a little funny in Fast graphics

### ISSUE THREAD

**Issue by FlameyFaucet** [alcatrazEscapee/primal-winter#52]
Yo, the snowy leaves render their leaves black when playing on Fast graphics. It returns to normal when on Fancy. Not really a big issue, but Fancy can wreck people's frames for those unfortunate enough to not have a very good PC.

**Comment by alcatrazEscapee** [comment]
This is due to the fact leaves use two layers - one that is colored (for the base leaf texture), and one that has the snow overlay, which relies on transparency layering (aka fancy graphics). I am not aware of any reasonable fix for this.
