### ISSUE TITLE
(Suggestion) Separate Pack Without Generation.

### ISSUE THREAD

**Issue by WolfzAtYT** [alcatrazEscapee/primal-winter#55]
I want to add something to my server for a christmas theme and I thought I'd use Primal Winter however it adds biome generation. I thought maybe it'd be a good idea to make a separate pack/mod that Is Primal Winter lite or something that only adds the snow mechanics and the fog. Thanks!

**Comment by alcatrazEscapee** [comment]
You can already blacklist any number of biomes, or use `nonWinterBiomes = []` and `invertNonWinterBiomes = true` (effectively turning it into a whitelist of no biomes). That will prevent any biome based modifications - but mind you, biome based modifications are *how some of this mod works*, i.e. the biome determines the temperature, and the weather (snow vs. rain).

I am not interested in making a "Lite" version of this mod.
