### ISSUE TITLE
How do you disable snow accumulation on certain blocks?

### ISSUE THREAD

**Issue by darchitectlp** [alcatrazEscapee/primal-winter#58]
I don't see anywhere in the config to disable snow accumulation. Is there a way to add specific blocks? Or to use a forge tag? Mostly I don't want snow accumulating on glass. Any way to do this?

**Comment by alcatrazEscapee** [comment]
There are two common config options for enabling snow accumulation: `enableSnowAccumulationDuringWorldgen` and `enableSnowAccumulationDuringWeather`, which are self explanatory. There is no way to add specific blocks. I suggest using a light source (see: vanilla)
