### ISSUE TITLE
Lag on server

### ISSUE THREAD

**Issue by RealSonarS** [alcatrazEscapee/primal-winter#61]
We're experiencing quite a bit of lag and after investigation realized it was due to a large amount of entities, due to there being no sunlight, they didn't die.

Is there a way to mitigate the lag while still keeping the snowstorm?

**Comment by alcatrazEscapee** [comment]
You're describing vanilla night time. I don't see how this mod plays into that at all - you'd be equally laggy, as per your diagnosis, simply by running `/weather thunder` and `/gamerule doWeatherCycle false`. In either case, it doesn't sound like an issue with Primal Winter, it sounds like an issue with your server, namely, it's lagging.
