### ISSUE TITLE
fog overwhelms screen and no access to config

### ISSUE THREAD

**Issue by Jhish** [alcatrazEscapee/primal-winter#62]
i just installed the newest 1.18.2 file today, and it seems that the fog completely covers my vision, and i do not have any settings to lower or disable it. i do not know how to access configuration of the mod files to manually decrease the fog level

**Comment by alcatrazEscapee** [comment]
This is likely caused by the `fogDensity` set by default to 0 instead of 0.1 - I do not know why this is happening but as of f37566893194ada51f698bfdb185bdd89336b3ba the config system will be entirely changing, so this issue will likely be moot.
