### ISSUE TITLE
World gen config Request

### ISSUE THREAD

**Issue by ogmon1243** [alcatrazEscapee/primal-winter#63]
Would it be possible to add a config option to allow what world gen structures are allowed to spawn in certain biomes and dimensions? An example would be having ice spikes spawn only spawn over oceans and no other biome or ice spikes in the overworld but not the end or any modded dimension in general. Maybe options to add more structures?

I am mainly requesting this because the ice spikes that generate conflict with a lot of modded structures and can grow pretty weirdly.

![2022-10-26_22 37 42](https://user-images.githubusercontent.com/83802482/198185569-9c06a925-e10c-455b-835e-aa6f30ebfb34.png)
weird ice spike gens like that in the twilight forest

**Comment by alcatrazEscapee** [comment]
You can already configure primal winter's world generation changes on a per-dimension and per-biome basis. If you want to have fine grained control, or modify the biomes yourself, that is also possible by directly modifying the biomes via datapack. I don't think I will add additional configuration options for convenience when that is all already possible.
