### ISSUE TITLE
Suggestion: Integration with Fabric Seasons

### ISSUE THREAD

**Issue by ghost** [alcatrazEscapee/primal-winter#65]
Hello,

Just an idea, it would be cool if there was an interaction with the Fabric Seasons mod, so that only during the winter does Primal Winter begin. The idea behind Fabric Seasons to me is that you only have a limited grow season, but the winter it creates isn't that intense. It would be cool if once the calendar ticked over Primal Winter engaged and the world became the intense snowscape it should be.

A really cool trio could be Seasons, Primal Winter, True Darkness, and some sort of Temperature mod. Just a thought, thanks for taking the time to read this!

**Comment by alcatrazEscapee** [comment]
No. Making the primal winter effects seasonal are both infeasible (i.e. replacements of many blocks during world generation cannot be simulated via effects, nor can runtime modifications of biomes), and not what this mod is about. There are mods that improve winter weather in smaller, transient methods - this is not one of them.
