### ISSUE TITLE
[1.18.2 FORGE] Snowing in Tropicraft dimension

### ISSUE THREAD

**Issue by S1mpleM0use** [alcatrazEscapee/primal-winter#66]
I've disabled snow accumulation and forced freezing of the dimension by adding everything in the config. ([attached](https://pastebin.com/JEDSuz76)) All entries were doublechecked
Yet, it still visually snows and the sky is gloomy.
![2022-12-03_11 54 03](https://user-images.githubusercontent.com/58431737/205432879-dfad79a2-3c95-4b43-857d-e0c519ba966c.png)
![2022-12-03_11 54 00](https://user-images.githubusercontent.com/58431737/205432882-c5e7479e-9b8e-432d-8f02-5ce3c4085f2d.png)

**Comment by S1mpleM0use** [comment]
In the Nether and in the End it doesn't snow visually

**Comment by S1mpleM0use** [comment]
I've changed the first one and the last two parameters in the config. Now it constantly rains. I can't change the weather by "/weather clear', even by enabling "weatherCycle" gamerule to "true".

**Comment by alcatrazEscapee** [comment]
#101
