### ISSUE TITLE
"Sounds" slowly rise up to 247 for no Reason in 1.18.2

### ISSUE THREAD

**Issue by JustFlakeZ** [alcatrazEscapee/primal-winter#67]
The Sounds Thingy slowly rises up to 247 by Time (after maybe half an Hour it reaches 247). U can also just stand still and do nothing and it would still happen. I also removed all my other Mods so it gotta be something wrong with Primal Winter
ill also post some Pictures

**Comment by JustFlakeZ** [comment]
![IMG_20221203_124635_194~2](https://user-images.githubusercontent.com/98987333/205439989-7a59bb2e-0a2a-4014-85f1-3928040ba119.jpg)
Before half an Hour

**Comment by JustFlakeZ** [comment]
![IMG_20221203_130033_927](https://user-images.githubusercontent.com/98987333/205440017-012c2651-e73b-4177-9f2c-a819eabcf641.jpg)
After half an Hour

**Comment by JustFlakeZ** [comment]
Also sorry for my English, ik its not that good

**Comment by wumengzhixing** [comment]
I have the same problem

**Comment by alcatrazEscapee** [comment]
Cannot reproduce on latest, after an hour of waiting in-game. Assuming it's been fixed since 1.18 as that version isn't being maintained.
