### ISSUE TITLE
Server crash with mod

### ISSUE THREAD

**Issue by Fadhvile** [alcatrazEscapee/primal-winter#68]
I try to made a server with the mod, and it'll just crash, I tried removing the mod one by one and find the server will turn on just fine without primalwinter.

Im using the forge-1.18.2-3.1.0. Version, here is the log

https://mclo.gs/rMl17YS

**Comment by Fadhvile** [comment]
I decide to test run again, but using the version forge-1.18.2-3.0.2, the server start fine

**Comment by alcatrazEscapee** [comment]
Duplicate of #69
