### ISSUE TITLE
[Suggestion] there is boss fight, to end and control the storm.

### ISSUE THREAD

**Issue by Worgrick** [alcatrazEscapee/primal-winter#7]
maybe it could be based on the whites from game of thrones.

**Comment by Worgrick** [comment]
you get an item after that turns on or off the weather, at the end on the boss fight.

**Comment by alcatrazEscapee** [comment]
I have no interest in adding anything of this form. From the technical side, the biome modifications are fairly invasive as is, and they really aren't designed to be modifiable during play. (For instance, what to do about all the snow blocks? They'd all just stay there, looking kind of weak). But more so to the fact that I have no particular expertise or ideas about how to design a compelling boss fight that would actually fit the theme of the mod. This is a very simple mod which basically changes the weather. Adding a boss (however lackluster) would feel tacked on.

I'd be very curious to see if this concept gets used by packs, and how it does end up. For example, using the biome whitelist, this could be used to create snowy "dimensions" and could very simply be used to "escape" the snowy dimension for something else.

**Comment by Worgrick** [comment]
I appreciate you looking at this the separate demetion would work, does it work for 1.16? And if so how would I do it?
