### ISSUE TITLE
Crashing with optifine

### ISSUE THREAD

**Issue by Sekyntosh** [alcatrazEscapee/primal-winter#70]
The game will initially close itself when loading a world with primal winter and optifine together.

Steps  to recreate.
1-install primal winther 1.19.2 and optifine 1.19.2.
2-open the game.
3-load a world.

upon starting the rendering of the player camera, the game will close throwing a array error.

**Comment by alcatrazEscapee** [comment]
Then don't use optifine. Unfortunately, optifine being a closed source invasive buggy mess, there's nothing I can or want to do to try and support it.
