### ISSUE TITLE
Mod doesn't work with one of these other Mods. (Mods are on the bottom of the Crash Report)

### ISSUE THREAD

**Issue by PLGC-AK47** [alcatrazEscapee/primal-winter#71]
Primal Winter doesn't seem to want to run with one of these mods. Sorry, I cant really pint-point which it doesn't work with. If anyone else had this problem, hopefully one of these mods we have is the same. 
[crash-2022-12-27_20.49.43-client.txt](https://github.com/alcatrazEscapee/primal-winter/files/10311589/crash-2022-12-27_20.49.43-client.txt)

**Comment by alcatrazEscapee** [comment]
This is an incompatibility with Serene Seasons. Using both mods together makes little sense and so I doubt I'll be fixing this - choose one of the two.
