### ISSUE TITLE
Different wheaters

### ISSUE THREAD

**Issue by DennisDv24** [alcatrazEscapee/primal-winter#75]
As a feature request, wouldnt it be nice if the mod had different wheaters? The default `fogDensity` looks nice but it can get boring quickly because of the limited view you get. It would be nice to have dynamic `fogDensity ` and `snowDensity` so sometimes you would get a better view of your world, but keeping the apocalyptic vibes.

**Comment by alcatrazEscapee** [comment]
No. The mod is primal winter. Not primal-most-of-the-time-but-actually-quite-varied-winter.
