### ISSUE TITLE
Can I change fog density in configs?

### ISSUE THREAD

**Issue by Pykrete13** [alcatrazEscapee/primal-winter#76]
I really like the idea of dense fog but it gets too claustrophobic for me over time. It reminds me of older versions bedrock fog down the mines. 
I'd like to wide a little field of view. 9 blocks feels too uncomfortable.

**Comment by alcatrazEscapee** [comment]
Yes... with the option `fogDensity`

**Comment by Pykrete13** [comment]
Can't find it in the code :(
Could you please show the path?
