### ISSUE TITLE
crashing while creating new world

### ISSUE THREAD

**Issue by kaserv** [alcatrazEscapee/primal-winter#77]
game version 1.19.2 forge

i believe it's a problem with this mod, since the world creating it was posible by extracting the primal winter mod from the mods carpet

here's the crash report if it helps with anything

[crash-2023-03-03_21.49.19-client.txt](https://github.com/alcatrazEscapee/primal-winter/files/10887297/crash-2023-03-03_21.49.19-client.txt)

also the mods list that i was using:

Tough As Nails
mobplaques
bagofholding
loot_journal
jei
puzzleslib
obscure_api
frosted_friends
sound_physics_remastered
gravestone
journeymap
aquamirae
strongersnowballs

**Comment by alcatrazEscapee** [comment]
Optifine is not supported - remove it and if see if the issue persists.
