### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by hydroid10** [alcatrazEscapee/primal-winter#78]
I don't know of any temperature mods that work with Primal Winter, so perhaps you could make one specifically for Primal Winter as it may add higher challenge to the already challenging environment. If not, then I'm not sure how to configure mods that add temperature to work with it, such as Tough As Nails, or Cold Sweat, which are the only two mods that I know of that adds temperature to Minecraft.

And as food for thought, if you go with that idea of adding a temperature system to Primal Winter (either integrated into the mod via a separate mod designed for it or part of a later version) you could even add some way to fight off the cold using thermal based tools and blocks. I remember there being a mob called the 'Blizz' which is basically the ice variant of the Blaze which drops blizz rods, that could be used for temperature based stuff, but that could be a seperate mod as well. It's up to you.

**Comment by alcatrazEscapee** [comment]
I have no plans to do any of this.
