### ISSUE TITLE
(1.18.2) Wrong particles in The End

### ISSUE THREAD

**Issue by Toastr125** [alcatrazEscapee/primal-winter#84]
I'm making a modpack on 1.18.2 where I have tweaked the end biomes to have rain via a datapack. I have blacklisted all end biomes in the biomes section of the config and blacklisted the end dimension in the dimensions section, but it still displays this mod's fast, dense snow effect around the player. Oddly enough, cauldrons fill with water and the splashes on the ground are water, so it seems the game does recognize it as raining. Additionally, the fog that this mod adds isn't there. I have checked other blacklisted dimensions and normal rain displays fine there, so this seems to be a purely visual bug that only happens in the end.

**Comment by Toastr125** [comment]
I wonder if this is related to the "Snowing in Tropicraft Dimension" issue

**Comment by alcatrazEscapee** [comment]
#101
