### ISSUE TITLE
Suggestion for snowy logs and config file issue

### ISSUE THREAD

**Issue by MrMartexX** [alcatrazEscapee/primal-winter#86]
I absolutely love this mod - it's the perfect addition to my Christmas-themed modpack.  But it lacks certain functionalities and configurability.

One issue is that villages and structures made of logs transform into a snowy variation, which looks a bit odd. Ice spikes can also appear inside and on top of other structures.

Additionally, despite my attempt to exclude specific overworld biomes from winter effects, logs and foliage within those biomes still appear in a snowy variation.

**Comment by alcatrazEscapee** [comment]
> One issue is that villages and structures made of logs transform into a snowy variation

This is not realistically fixable, and generally intended. They didn't _grow_ that way, they froze.

> Ice spikes can also appear inside and on top of other structures.

This is a quirk of vanilla generation too, they're just much more common here

> Additionally, despite my attempt to exclude specific overworld biomes from winter effects

See #101, but ultimately blacklisting will not function the way you are trying to make it work.
