### ISSUE TITLE
Can't add modded biomes or dimensions

### ISSUE THREAD

**Issue by ArtemHOTA** [alcatrazEscapee/primal-winter#92]
I wanted no snow in the dimensions, so I changed invertNonWinterBiomes to true and invertNonWinterDimensions to true, and it worked. But when i wanted to add dimensions or biomes (in my case "aether:the_aether" and some incendium biomes, the whole world had no snow. Pretty much i broke the config, but i still want to know what's wrong

**Comment by alcatrazEscapee** [comment]
As I'm not magic and can't see inside your config file, I cannot tell you what's wrong. There seems to be some issue w.r.t dimension/biome blacklisting you might be running into. See #101
