### ISSUE TITLE
where in the world is the config

### ISSUE THREAD

**Issue by Rouge-Pharsh** [alcatrazEscapee/primal-winter#93]
i genuinly cannot see anything with the fog and wish to turn it off for my modpack i read readme which is what it told me to do and i found nothing about config so maybe a bit of help here

**Comment by Rouge-Pharsh** [comment]
okay found the config but no way to turn off the fog and setting it ridiculously high fixes nothing

**Comment by Rouge-Pharsh** [comment]
okay another update realizing my low render distance was the thing screwing me over genuinely made me feel as stupid as a donkey

**Comment by alcatrazEscapee** [comment]
Seems resolved then.
