### ISSUE TITLE
Consider giving villagers, iron golems, cats and wolves the `minecraft:powder_snow_walkable_mobs` and `minecraft:freeze_immune_entity_types` entity tags

### ISSUE THREAD

**Issue by PinkDisorder** [alcatrazEscapee/primal-winter#94]
As it stands, any village will be rapidly emptied of all life shortly after visiting it, due to the resident entities getting stuck in the powder snow which is _everywhere_ and freezing to death. Giving them the tags above would fix the issue.

**Comment by PinkDisorder** [comment]
As a temporary workaround, modpack authors, players, server owners, etc can include the following kubejs script inside of their server scripts:
```js
const unfreezables = [
  "minecraft:cat",
  "minecraft:villager",
  "minecraft:wandering_trader",
  "minecraft:iron_golem",
  "minecraft:llama",
  "minecraft:trader_llama",
  "minecraft:wolf",
];

ServerEvents.tags("entity_type", function (event) {
  unfreezables.forEach(entity => {
    event.add("minecraft:freeze_immune_entity_types", entity);
    event.add("minecraft:powder_snow_walkable_mobs", entity);
  });
});
```
You can also add the following piece of code to turn every villager into the snowy variant.
```js
const villagerNbtFix = {
  VillagerData: {
    type: "minecraft:snow"
  }
};

EntityEvents.spawned("minecraft:villager", evt => evt.entity.mergeNbt(villagerNbtFix));
```

**Comment by crushthatdwarf** [comment]
Might be good to add the following to that no-freeze list, just to keep things interesting. If one is so inclined.
- "minecraft:pillager",
- "minecraft:witch",
- "minecraft:vindicator"

**Comment by crushthatdwarf** [comment]
Might be good to add the following to that no-freeze list, just to keep things interesting. If one is so inclined.
- "minecraft:pillager"
- "minecraft:witch"
- "minecraft:vindicator"

**Comment by alcatrazEscapee** [comment]
I don't see a reason why these mobs should be immune - the whole point is to create a very harsh world (similarly, I'm not forcing passive mobs to spawn - they are _much_ more rare and difficult to obtain.

Doing this for aggressive mobs I like because it fits the theme, though would be nice to get snow-themed skins for the pillager/witch/vindicator...

**Comment by PinkDisorder** [comment]
> I don't see a reason why these mobs should be immune

Villagers: since a snowy variant exists it would make sense for them to be adapted to the weather conditions. It makes little sense for the villagers to be opening their doors and walking into the deep snow to die immediately.

Iron Golems: doesn't really make much sense for an iron construct to just die in the snow. A slowness debuff would make sense though, for frozen joints and for slugging through the deep snow in general.

Wolves: wolves commonly inhabit areas that see heavy snowfall, in real life. In Minecraft they spawn in the colder biomes. It makes little sense for them to just die to a little snow.

Llamas irl live in high altitude cold areas and grow the thick fur we all know about.

Wandering traders... You'd think they'd be prepared to tackle the weather if they go wandering to trade, no?

Cats: not much reason to make them immune, I agree. However it would prevent the feeling of jank cause they do spawn in villages.
