### ISSUE TITLE
Нету снега 

### ISSUE THREAD

**Issue by Dimiki** [alcatrazEscapee/primal-winter#96]
Выключил мод и зашел в мир снег багнулся но я понял как его починить когда вернул мо понял что снега и даже холода нет шол обычный дождь нашел 1 команду /snow +(сколько блоков) -s как включить снег так и не понял в других мирах и вновь созданных тоже снега нет что делать не знаю? Может стоит перезагрузить мод?

**Comment by alcatrazEscapee** [comment]
I can't do anything with this issue report
