### ISSUE TITLE
Snow generates inside closed structures

### ISSUE THREAD

**Issue by LeviMeyers** [alcatrazEscapee/primal-winter#97]
Something with how the freeze top layer function works makes it so that every structure generated on the surface has a snow layer inside on the floor. Mainly found this because of structure mods but it seems to happen the same way with vanilla villages as well.

**Comment by alcatrazEscapee** [comment]
This is generally intended - it's how snow creeps inside cave entrances, under overhangs, and is part of primal winter's more aggressive snowfall world generation.
