### ISSUE TITLE
Suggestion - Make grass decay

### ISSUE THREAD

**Issue by estebangames842** [alcatrazEscapee/primal-winter#98]
I've decided to turn some old worlds into Primal Winter survival worlds, by adding the mod mid playthrough. 
It all works fine except that grass does not decay, preventing snow from falling on top of it, which creates very annoying "potholes" in the snow.
I believe making grass/tall grass decay over time (sorta how leaves decay when no log is present) would fix this sort of thing.

I think this is more of a suggestion than a fix because i bet this isn't the intended use of the mod lol

**Comment by alcatrazEscapee** [comment]
No, retroactively fixing existing worlds is not part of the plan for this mod.
